### ISSUE TITLE
İts Work but,"read" does not work when video is open

### ISSUE THREAD

**Issue by maaami98** [CBiX/gotubecast#11]
cmd:video_id arg:VvjePRvHq8E
omxplayer.bin: no process found
Video codec omx-h264 width 640 height 360 profile 578 fps 25.000000
Audio codec aac channels 2 samplerate 44100 bitspersample 16
Subtitle count: 0, state: off, index: 1, delay: 0
V:PortSettingsChanged: 640x360@25.00 interlace:0 deinterlace:0 anaglyph:0 par:1.12 display:0 layer:0 alpha:255 aspectMode:0
cmd:seek_to arg:37
Seek to: 00:00:37
./youtube.sh: satır 24: read: okuma hatası: 0: Özkaynak geçici olarak kullanılamaz durumda

**Comment by maaami98** [comment]
replace "omxplayer $OMX_OPTS "$YTURL" &"     to "omxplayer $OMX_OPTS "$YTURL" </dev/null&"

**Comment by cbix** [comment]
Thanks for this, I didn't test the script in a long time and YT probably sometimes changes the protocol or sth, so I'll test and change this as soon as possible!
