### ISSUE TITLE
gotubecast crashes when choosing "Play All Now" on Youtube playlist

### ISSUE THREAD

**Issue by mervin39** [CBiX/gotubecast#2]
Firstly, thank you for gotubecast. It is exactly what I have been looking for!

When I send a Youtube playlist/mix to gotubecast with the "Play All Now" option, it crashes with the following output:

`panic: interface conversion: interface is nil, not string

goroutine 1 [running]:
panic(0x2d9410, 0x109704c0)
	/usr/lib/go-1.6/src/runtime/panic.go:481 +0x330
main.genericCmd(0xc, 0x0, 0x108cfbc0, 0xb, 0x108cfc28, 0x1, 0x1)
	/usr/bin/gotubecast/main.go:294 +0x3724
main.decodeBindStream(0x76f36ba0, 0x109340a0, 0x0, 0x0)
	/usr/bin/gotubecast/main.go:233 +0x3f4
main.main()
	/usr/bin/gotubecast/main.go:191 +0x18c4`

**Comment by cbix** [comment]
Ooop, just tried and still have this issue. Reopened.

**Comment by mervin39** [comment]
This is working for me now for playlists, but fails in the same manner for Youtube "mixes". I never realised they were different!

**Comment by cbix** [comment]
Can you provide an example mix link where it fails? Are you on Android or iOS? Did you pull the latest commits and build again?

**Comment by mervin39** [comment]
Apologies, my mistake. I've built again and it's working great. Thanks!
