### ISSUE TITLE
panic: invalid character

### ISSUE THREAD

**Issue by HappySlappyTiime** [CBiX/gotubecast#21]
gotubecast was working fine for me. Now suddenly i get the error Message as soon as i click on the Youtubevideo on my Phone, and the script crashes.

`remote_join D8ACEB80-FF51-4F15-BD65-C4D8352D20DC HappySlappyTiime
generic_cmd getSubtitlesTrack []
user_action
panic: invalid character '<' looking for beginning of value

goroutine 1 [running]:
main.getListInfo(0x26b64a0, 0x1d, 0x23ea47)
        /home/pi/go/src/github.com/CBiX/gotubecast/main.go:501 +0x1e4
main.genericCmd(0xb, 0x0, 0x26e2500, 0xb, 0x26e44c8, 0x1, 0x1)
        /home/pi/go/src/github.com/CBiX/gotubecast/main.go:289 +0x2550
main.decodeBindStream(0x63f19350, 0x25c26e0, 0x25c26e0, 0x63f19350)
        /home/pi/go/src/github.com/CBiX/gotubecast/main.go:233 +0x100
main.main()
        /home/pi/go/src/github.com/CBiX/gotubecast/main.go:191 +0x115c
`

Tried reinstalling completly, nothing worked. I'm sure theres a simple fix to that i'm just not that advanced :P

**Comment by vviikk** [comment]
Same issue here. And same problem with not being advanced enough.

**Comment by FlowH4ck** [comment]
Wassup there! Same problem, used golang v16.2, v11.1
kick me when the fierce discussion begins :)

**Comment by cbix** [comment]
Sorry for the late reply. I'm not actively using gotubecast myself, but I'll look into it!

**Comment by cbix** [comment]
Just pushed a hotfix and initialized gotubecast as a go module (see updated README).

Some things might not work now, but at least it doesn't crash when you play a video.

Thanks for the reports!
