### ISSUE TITLE
Can't build

### ISSUE THREAD

**Issue by ScttB** [CBiX/gotubecast#4]
```
root@raspberrypi:/home/pi/coolio/gotubecast# go build
# _/home/pi/coolio/gotubecast
./main.go:208: undefined: json.Token
./main.go:209: dec.Token undefined (type *json.Decoder has no field or method Token)
./main.go:220: undefined: json.Delim
./main.go:221: dec.More undefined (type *json.Decoder has no field or method More)
./main.go:236: dec.Token undefined (type *json.Decoder has no field or method Token)
```
Did I miss something in the [instructions?](https://www.raspberrypi.org/forums/viewtopic.php?f=35&t=159729)

**Comment by cbix** [comment]
I cannot reproduce it. Which go version are you using?

    go version

**Comment by ScttB** [comment]
The latest version of golang on Raspian repositories as far as I know.
```
root@raspberrypi:/home/pi# go version
go version go1.3.3 linux/arm
```

**Comment by d0uub** [comment]
same here

**Comment by cbix** [comment]
Ok, I tried building with go 1.3.3 and get the same error now. Looks like json.Token was not supported by that version yet. I cross-compiled for Raspberry Pi from go 1.9.1 and attached the binary for you (in a zip): 
[gotubecast-arm-go1.9.1.zip](https://github.com/CBiX/gotubecast/files/1425368/gotubecast-arm-go1.9.1.zip)
Should work as it's statically linked :)

If you want to compile it yourself on the Pi, try to get a newer version of go installed.

**Comment by d0uub** [comment]
thanks!

**Comment by 1GR3** [comment]
Thank you for recompiling but I've got an error:
`$ bash gotubecast
gotubecast: gotubecast: cannot execute binary file`

**Comment by cbix** [comment]
@1GR3 
> `gotubecast: cannot execute binary file`

The binary is for Raspberry Pi.

**Comment by 1GR3** [comment]
> @1GR3
> 
> > `gotubecast: cannot execute binary file`
> 
> The binary is for Raspberry Pi.

I'm aware of that. I've tried to compile it in Raspbian but ended up here. Am I missing something in configurations?

**Comment by cbix** [comment]
Can you post the output of `file gotubecast` and `uname -a`? Thanks!
